type: object
properties:
  id:
    type: string
  coordinates:
    type: array
    items:
      type: number
      format: float
    description: The coordinates where the package should be delivered.
    example: [1, 1, 0.5]
  weight:
    type: number
    format: integer
    description: The total weight of the package.
